# Creating Tensors

In [2]:
import torch
print(torch.__version__)

2.10.0+cu128


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Device name {torch.cuda.get_device_name(0)}")

else:
    print("GPU is not available")

GPU is available
Device name Tesla T4


In [4]:
a = torch.empty(2, 3)
a

tensor([[-1.5293e-28,  4.5338e-41, -1.5293e-28],
        [ 4.5338e-41,  0.0000e+00,  0.0000e+00]])

In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2, 3)

tensor([[0.8461, 0.1594, 0.9800],
        [0.1509, 0.8727, 0.4916]])

In [9]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.tensor([ [1, 2, 3], [4, 5, 6] ])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
torch.arange(0, 11, 2)

tensor([ 0,  2,  4,  6,  8, 10])

In [13]:
torch.linspace(1, 10, 7)

tensor([ 1.0000,  2.5000,  4.0000,  5.5000,  7.0000,  8.5000, 10.0000])

# Tensors Shape

In [14]:
X = torch.tensor([ [1, 2, 3], [4, 5, 6] ])
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
X.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(X)

tensor([[0, 0, 0],
        [0, 1, 0]])

In [17]:
torch.ones_like(X)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(X, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensors data types

In [19]:
X.dtype

torch.int64

In [20]:
torch.tensor([1.5, 2.5, 3.5, 4.5, 5.5],  dtype=torch.int32)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [21]:
X = X.to(torch.float32)

In [22]:
X.dtype

torch.float32

# Math Scaler Operations

In [23]:
x = torch.tensor([[2, 4, 6], [6, 8, 10]])
x

tensor([[ 2,  4,  6],
        [ 6,  8, 10]])

In [24]:
x+2

tensor([[ 4,  6,  8],
        [ 8, 10, 12]])

In [25]:
x-2

tensor([[0, 2, 4],
        [4, 6, 8]])

In [26]:
x*2

tensor([[ 4,  8, 12],
        [12, 16, 20]])

In [27]:
x/2

tensor([[1., 2., 3.],
        [3., 4., 5.]])

In [28]:
x**2

tensor([[  4,  16,  36],
        [ 36,  64, 100]])

In [29]:
x%2

tensor([[0, 0, 0],
        [0, 0, 0]])

# Math Element Wise Operation

In [30]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

In [31]:
b

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [32]:
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [33]:
a-b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [34]:
a*b

tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])

In [35]:
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [36]:
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [37]:
a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [38]:
c = torch.tensor([-1, -2, -3, -4, -5])

In [39]:
torch.abs(c)

tensor([1, 2, 3, 4, 5])

In [40]:
torch.neg(c)

tensor([1, 2, 3, 4, 5])

In [41]:
d = torch.tensor([1.2, 4.5, 6.7, 8.9])

In [42]:
torch.ceil(d)

tensor([2., 5., 7., 9.])

In [43]:
torch.floor(d)

tensor([1., 4., 6., 8.])

In [44]:
torch.clamp(d, min=1, max=5)

tensor([1.2000, 4.5000, 5.0000, 5.0000])

# Math Reduction Operations

In [45]:
e = torch.randint(size=(2,3), low=1, high=10, dtype=torch.float32)

In [46]:
e

tensor([[2., 4., 7.],
        [4., 7., 8.]])

In [47]:
torch.sum(e)

tensor(32.)

In [48]:
torch.sum(e, dim=0)

tensor([ 6., 11., 15.])

In [49]:
torch.sum(e, dim=1)

tensor([13., 19.])

In [50]:
torch.mean(e)

tensor(5.3333)

In [51]:
torch.median(e)

tensor(4.)

In [52]:
torch.max(e)

tensor(8.)

In [53]:
torch.min(e)

tensor(2.)

In [54]:
torch.prod(e)

tensor(12544.)

In [55]:
torch.std(e)

tensor(2.3381)

In [56]:
torch.var(e)

tensor(5.4667)

In [57]:
torch.argmax(e)

tensor(5)

In [58]:
torch.argmin(e)

tensor(0)

# Math matrix opertions

In [59]:
f = torch.randint(size=(2, 3), low=1, high=10)
g = torch.randint(size=(3, 2), low=1, high=10)

In [60]:
f

tensor([[8, 6, 7],
        [9, 3, 7]])

In [61]:
g

tensor([[7, 4],
        [9, 3],
        [7, 6]])

In [62]:
torch.matmul(f, g)

tensor([[159,  92],
        [139,  87]])

In [63]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [64]:
torch.dot(vector1, vector2)

tensor(11)

In [65]:
f

tensor([[8, 6, 7],
        [9, 3, 7]])

In [66]:
torch.transpose(f, 0, 1)

tensor([[8, 9],
        [6, 3],
        [7, 7]])

# Comparision Operations

In [67]:
i = torch.randint(size=(2, 3), low=0, high=10)
j = torch.randint(size=(2, 3), low=0, high=10)

In [68]:
i

tensor([[5, 9, 9],
        [7, 5, 9]])

In [69]:
j

tensor([[8, 9, 7],
        [9, 2, 6]])

In [70]:
i > j

tensor([[False, False,  True],
        [False,  True,  True]])

In [71]:
i < j

tensor([[ True, False, False],
        [ True, False, False]])

In [72]:
i == j

tensor([[False,  True, False],
        [False, False, False]])

In [73]:
i != j

tensor([[ True, False,  True],
        [ True,  True,  True]])

# Special Functions

In [74]:
k = torch.tensor([10, 20, 30])
k

tensor([10, 20, 30])

In [75]:
torch.log(k)

tensor([2.3026, 2.9957, 3.4012])

In [76]:
torch.exp(k)

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13])

In [77]:
torch.sqrt(k)

tensor([3.1623, 4.4721, 5.4772])

In [78]:
torch.sigmoid(k)

tensor([1.0000, 1.0000, 1.0000])

In [79]:
torch.softmax(k.float(), dim=0)

tensor([2.0611e-09, 4.5398e-05, 9.9995e-01])

In [80]:
torch.relu(k)

tensor([10, 20, 30])

# Inplace operations

In [81]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [82]:
b = a + 5
b

tensor([6, 7, 8])

In [83]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

In [84]:
m

tensor([[0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356]])

In [85]:
n

tensor([[0.3039, 0.6726, 0.5740],
        [0.9233, 0.9178, 0.7590]])

In [86]:
m.add_(n)

tensor([[0.9251, 1.2256, 1.2636],
        [1.2920, 1.8231, 1.5946]])

In [87]:
torch.relu_(m)

tensor([[0.9251, 1.2256, 1.2636],
        [1.2920, 1.8231, 1.5946]])

In [88]:
m.relu_()

tensor([[0.9251, 1.2256, 1.2636],
        [1.2920, 1.8231, 1.5946]])

# Copying a tensor

In [89]:
a = torch.tensor([1, 2, 3, 4, 5])
a

tensor([1, 2, 3, 4, 5])

In [90]:
b = a

In [91]:
b[2] = 30

In [92]:
b

tensor([ 1,  2, 30,  4,  5])

In [93]:
a

tensor([ 1,  2, 30,  4,  5])

In [94]:
b = a.clone()
b

tensor([ 1,  2, 30,  4,  5])